# Generated by Django 4.2.6 on 2023-10-25 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.TextField(default=None)),
                ('descriere', models.TextField(default=None)),
                ('score', models.TextField(default=None)),
                ('regizor', models.TextField(default=None)),
                ('star', models.TextField(default=None)),
                ('storyline', models.TextField(default=None)),
                ('data', models.DateField(default=None)),
                ('durata', models.DurationField(default=None)),
                ('azi', models.BooleanField(default=False)),
                ('imagine', models.ImageField(upload_to='static/images')),
                ('ora1', models.TimeField(default=None)),
                ('ora2', models.TimeField(default=None)),
                ('trailer_link', models.TextField(default=None)),
                ('id_gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filme.gen')),
            ],
        ),
    ]
